name: Release and Deploy
on:
  - push
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Write release result to file
        run: mkdir release
      - name: Write Published
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: 'release.properties'
          property: 'published'
          value: ${{ steps.semantic.outputs.new_release_published }}
      - name: Write Version
        uses: christian-draeger/write-properties@1.0.1
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          path: 'release.properties'
          property: 'version'
          value: ${{ steps.semantic.outputs.new_release_version }}
      - name: Share release file with other jobs
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: 'release.properties'
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04,ubuntu-16.04 ]
    needs: release
    name: Deploy if released
    steps:
      - name: Download release
        uses: actions/download-artifact@v1
        with:
          name: release
      - name: Read Published
        id: published
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'release/release.properties'
          property: 'published'
      - run: echo published=${{ steps.published.outputs.value }}
      - name: Read Version
        id: version
        if: steps.published.outputs.value == 'true'
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'release/release.properties'
          property: 'version'
      - name: Deploy
        if: steps.published.outputs.value == 'true'
        run: echo Deploying ${{ steps.version.outputs.value }}
